version: '3.4'

services:
  productioncontrol.apigateways:
    image: ${DOCKER_REGISTRY-}productioncontrolapigateways
    container_name: productioncontrol.apigateways
    hostname: productioncontrol.apigateways
    build:
      context: .
      dockerfile: src/Backends/Services/ApiGateway/Dockerfile

  productioncontrol.orders:
    image: ${DOCKER_REGISTRY-}productioncontrolorders
    container_name: productioncontrol.orders
    hostname: productioncontrol.orders
    build:
      context: .
      dockerfile: src/Backends/Services/Order/Dockerfile


  #productioncontrol.masters:
  #  image: ${DOCKER_REGISTRY-}productioncontrolmasters
  #  container_name: productioncontrol.masters
  #  hostname: productioncontrol.masters
  #  build:
  #    context: ../..
  #    dockerfile: src/Backends/Services/Masters/Dockerfile

